---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/languages":
    get:
      summary: list languages
      parameters:
      - name: token
        in: header
        schema:
          type: string
      responses:
        '200':
          description: successful
  "/current_language":
    get:
      summary: current_language language
      parameters:
      - name: token
        in: header
        schema:
          type: string
      responses:
        '200':
          description: successful
  "/update_current_language":
    put:
      summary: update_current_language language
      parameters:
      - name: token
        in: header
        schema:
          type: string
      responses:
        '200':
          description: successful
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000/
